[package]
name = "drone"
version = "0.1.0"
authors = ["Thomas Deegan <tadeegan@gmail.com>", "Martin Deegan <mddeegan@gmail.com>"]

[dependencies]
rust-pigpio = "0.2.0"
sensors = {path = "./sensors", version = "0.1.0"}
time = "0.1"

[[bin]]
name = "drone"
path = "src/main.rs"
